[package]
name = "bytepath_tutorial"
version = "0.1.0"
authors = ["Jakob Schwab <j.schwab@mail.de>"]
edition = "2018"
default-run = "bytepath_tutorial"

[dependencies.ct_lib]
path = "../cottontail/ct_lib"

[dependencies.ct_platform]
path = "../cottontail/ct_platform"

[dependencies]